/*
* generated by Xtext
*/
package org.franca.core.dsl.ui.contentassist;

import org.franca.core.dsl.ui.contentassist.AbstractFrancaIDLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FrancaIDLProposalProvider extends AbstractFrancaIDLProposalProvider {

}
