/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.ProtobufSpec'
*******************************************************************************/
package org.franca.connectors.protobuf;

import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.ProtobufSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.ProtobufSpec.TypeCollectionPropertyAccessor instead
 */
public class ProtobufSpecTypeCollectionPropertyAccessor
	extends org.franca.connectors.protobuf.ProtobufSpec.TypeCollectionPropertyAccessor
	implements org.franca.connectors.protobuf.ProtobufSpec.Enums
{
	public ProtobufSpecTypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
		super(target);
	}
}
   
