/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.ProtobufSpec'
*******************************************************************************/
package org.franca.connectors.protobuf;

import java.util.Map;

import org.franca.core.franca.FArgument;
import org.franca.core.franca.FArrayType;
import org.franca.core.franca.FAttribute;
import org.franca.core.franca.FEnumerator;
import org.franca.core.franca.FField;
import org.franca.core.franca.FModelElement;
import org.franca.core.franca.FStructType;
import org.franca.deploymodel.core.FDeployedInterface;
import org.franca.deploymodel.core.FDeployedProvider;
import org.franca.deploymodel.core.FDeployedTypeCollection;
import org.franca.deploymodel.core.MappingGenericPropertyAccessor;
import org.franca.deploymodel.dsl.fDeploy.FDCompoundOverwrites;
import org.franca.deploymodel.dsl.fDeploy.FDEnumValue;
import org.franca.deploymodel.dsl.fDeploy.FDEnumerationOverwrites;
import org.franca.deploymodel.dsl.fDeploy.FDField;
import org.franca.deploymodel.dsl.fDeploy.FDOverwriteElement;
import org.franca.deploymodel.dsl.fDeploy.FDTypeOverwrites;

import com.google.common.collect.Maps;

/**
 * This is a collection of all interfaces and classes needed for
 * accessing deployment properties according to deployment specification
 * 'org.franca.connectors.protobuf.ProtobufSpec'.
 */
public class ProtobufSpec {

	/**
	 * Enumerations for deployment specification org.franca.connectors.protobuf.ProtobufSpec.
	 */
	public interface Enums
	{
		public enum Ctype {
			CORD, STRING, STRING_PIECE
		}
		 
	}

	/**
	 * Interface for data deployment properties for 'org.franca.connectors.protobuf.ProtobufSpec' specification
	 * 
	 * This is the data types related part only.
	 */
	public interface IDataPropertyAccessor
		extends Enums
	{
		// host 'struct_fields'
		public Integer getTag(FField obj);
		public Boolean getIsOptional(FField obj);
		public String getDefaultValue(FField obj);
		public Ctype getCtype(FField obj);
		public Boolean getPacked(FField obj);
		public String getExperimental_map_key(FField obj);
		
		// host 'structs'
		public Boolean getMessage_set_wire_format(FStructType obj);
		public Boolean getNo_standard_descriptor_accessor(FStructType obj);
		
		
		/**
		 * Get an overwrite-aware accessor for deployment properties.</p>
		 *
		 * This accessor will return overwritten property values in the context 
		 * of a Franca FField object. I.e., the FField obj has a datatype
		 * which can be overwritten in the deployment definition (e.g., Franca array,
		 * struct, union or enumeration). The accessor will return the overwritten values.
		 * If the deployment definition didn't overwrite the value, this accessor will
		 * delegate to its parent accessor.</p>
		 *
		 * @param obj a Franca FField which is the context for the accessor
		 * @return the overwrite-aware accessor
		 */
		public IDataPropertyAccessor getOverwriteAccessor(FField obj);
	
		/**
		 * Get an overwrite-aware accessor for deployment properties.</p>
		 *
		 * This accessor will return overwritten property values in the context 
		 * of a Franca FArrayType object. I.e., the FArrayType obj has a datatype
		 * which can be overwritten in the deployment definition (e.g., Franca array,
		 * struct, union or enumeration). The accessor will return the overwritten values.
		 * If the deployment definition didn't overwrite the value, this accessor will
		 * delegate to its parent accessor.</p>
		 *
		 * @param obj a Franca FArrayType which is the context for the accessor
		 * @return the overwrite-aware accessor
		 */
		public IDataPropertyAccessor getOverwriteAccessor(FArrayType obj);
	}

	/**
	 * Helper class for data-related property accessors.
	 */		
	public static class DataPropertyAccessorHelper implements Enums
	{
		final private MappingGenericPropertyAccessor target;
		final private IDataPropertyAccessor owner;
		
		public DataPropertyAccessorHelper(
			MappingGenericPropertyAccessor target,
			IDataPropertyAccessor owner
		) {
			this.target = target;
			this.owner = owner;
		}
	
		public static Ctype convertCtype(String val) {
			if (val.equals("CORD"))
				return Ctype.CORD; else 
			if (val.equals("STRING"))
				return Ctype.STRING; else 
			if (val.equals("STRING_PIECE"))
				return Ctype.STRING_PIECE;
			return null;
		}
		
		
		protected IDataPropertyAccessor getOverwriteAccessorAux(FModelElement obj) {
			FDOverwriteElement fd = (FDOverwriteElement)target.getFDElement(obj);
			FDTypeOverwrites overwrites = fd.getOverwrites();
			if (overwrites==null)
				return owner;
			else
				return new OverwriteAccessor(overwrites, owner, target);
		}
	}

	/**
	 * Accessor for deployment properties for Franca type collections according
	 * to deployment specification 'org.franca.connectors.protobuf.ProtobufSpec'.
	 */		
	public static class TypeCollectionPropertyAccessor
		implements IDataPropertyAccessor
	{
		final private MappingGenericPropertyAccessor target;
		private final DataPropertyAccessorHelper helper;
	
		public TypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
			this.target = target;
			this.helper = new DataPropertyAccessorHelper(target, this);
		}
		
		// host 'struct_fields'
		@Override
		public Integer getTag(FField obj) {
			return target.getInteger(obj, "Tag");
		}
		@Override
		public Boolean getIsOptional(FField obj) {
			return target.getBoolean(obj, "IsOptional");
		}
		@Override
		public String getDefaultValue(FField obj) {
			return target.getString(obj, "DefaultValue");
		}
		@Override
		public Ctype getCtype(FField obj) {
			String e = target.getEnum(obj, "Ctype");
			if (e==null) return null;
			return DataPropertyAccessorHelper.convertCtype(e);
		}
		@Override
		public Boolean getPacked(FField obj) {
			return target.getBoolean(obj, "Packed");
		}
		@Override
		public String getExperimental_map_key(FField obj) {
			return target.getString(obj, "Experimental_map_key");
		}
		
		// host 'structs'
		@Override
		public Boolean getMessage_set_wire_format(FStructType obj) {
			return target.getBoolean(obj, "Message_set_wire_format");
		}
		@Override
		public Boolean getNo_standard_descriptor_accessor(FStructType obj) {
			return target.getBoolean(obj, "No_standard_descriptor_accessor");
		}
		
		
		@Override
		public IDataPropertyAccessor getOverwriteAccessor(FField obj) {
			return helper.getOverwriteAccessorAux(obj);
		}
	
		@Override
		public IDataPropertyAccessor getOverwriteAccessor(FArrayType obj) {
			return helper.getOverwriteAccessorAux(obj);
		}
	}

	/**
	 * Accessor for deployment properties for Franca interfaces according to
	 * deployment specification 'org.franca.connectors.protobuf.ProtobufSpec'.
	 */
	public static class InterfacePropertyAccessor
		implements IDataPropertyAccessor
	{
		final private MappingGenericPropertyAccessor target;
		private final DataPropertyAccessorHelper helper;
	
		public InterfacePropertyAccessor(FDeployedInterface target) {
			this.target = target;
			this.helper = new DataPropertyAccessorHelper(target, this);
		}
		
		// host 'struct_fields'
		@Override
		public Integer getTag(FField obj) {
			return target.getInteger(obj, "Tag");
		}
		@Override
		public Boolean getIsOptional(FField obj) {
			return target.getBoolean(obj, "IsOptional");
		}
		@Override
		public String getDefaultValue(FField obj) {
			return target.getString(obj, "DefaultValue");
		}
		@Override
		public Ctype getCtype(FField obj) {
			String e = target.getEnum(obj, "Ctype");
			if (e==null) return null;
			return DataPropertyAccessorHelper.convertCtype(e);
		}
		@Override
		public Boolean getPacked(FField obj) {
			return target.getBoolean(obj, "Packed");
		}
		@Override
		public String getExperimental_map_key(FField obj) {
			return target.getString(obj, "Experimental_map_key");
		}
		
		// host 'structs'
		@Override
		public Boolean getMessage_set_wire_format(FStructType obj) {
			return target.getBoolean(obj, "Message_set_wire_format");
		}
		@Override
		public Boolean getNo_standard_descriptor_accessor(FStructType obj) {
			return target.getBoolean(obj, "No_standard_descriptor_accessor");
		}
		
		
		/**
		 * Get an overwrite-aware accessor for deployment properties.</p>
		 *
		 * This accessor will return overwritten property values in the context 
		 * of a Franca FAttribute object. I.e., the FAttribute obj has a datatype
		 * which can be overwritten in the deployment definition (e.g., Franca array,
		 * struct, union or enumeration). The accessor will return the overwritten values.
		 * If the deployment definition didn't overwrite the value, this accessor will
		 * delegate to its parent accessor.</p>
		 *
		 * @param obj a Franca FAttribute which is the context for the accessor
		 * @return the overwrite-aware accessor
		 */
		public IDataPropertyAccessor getOverwriteAccessor(FAttribute obj) {
			return helper.getOverwriteAccessorAux(obj);
		}
	
		/**
		 * Get an overwrite-aware accessor for deployment properties.</p>
		 *
		 * This accessor will return overwritten property values in the context 
		 * of a Franca FArgument object. I.e., the FArgument obj has a datatype
		 * which can be overwritten in the deployment definition (e.g., Franca array,
		 * struct, union or enumeration). The accessor will return the overwritten values.
		 * If the deployment definition didn't overwrite the value, this accessor will
		 * delegate to its parent accessor.</p>
		 *
		 * @param obj a Franca FArgument which is the context for the accessor
		 * @return the overwrite-aware accessor
		 */
		public IDataPropertyAccessor getOverwriteAccessor(FArgument obj) {
			return helper.getOverwriteAccessorAux(obj);
		}
	
		@Override
		public IDataPropertyAccessor getOverwriteAccessor(FField obj) {
			return helper.getOverwriteAccessorAux(obj);
		}
	
		@Override
		public IDataPropertyAccessor getOverwriteAccessor(FArrayType obj) {
			return helper.getOverwriteAccessorAux(obj);
		}
	}

	/**
	 * Accessor for deployment properties for providers and interface instances
	 * according to the 'org.franca.connectors.protobuf.ProtobufSpec' specification.
	 */
	public static class ProviderPropertyAccessor
		implements Enums
	{
		final private FDeployedProvider target;
	
		public ProviderPropertyAccessor(FDeployedProvider target) {
			this.target = target;
		}
		
	}

	/**
	 * Accessor for getting overwritten property values.
	 */		
	public static class OverwriteAccessor
		implements IDataPropertyAccessor
	{
		private final MappingGenericPropertyAccessor target;
		private final IDataPropertyAccessor delegate;
		
		private final FDTypeOverwrites overwrites;
		private final Map<FField, FDField> mappedFields;
		private final Map<FEnumerator, FDEnumValue> mappedEnumerators;
		private final DataPropertyAccessorHelper helper;
	
		public OverwriteAccessor(
				FDTypeOverwrites overwrites,
				IDataPropertyAccessor delegate,
				MappingGenericPropertyAccessor genericAccessor)
		{
			this.target = genericAccessor;
			this.delegate = delegate;
			this.helper = new DataPropertyAccessorHelper(genericAccessor, this);
	
			this.overwrites = overwrites;
			this.mappedFields = Maps.newHashMap();
			this.mappedEnumerators = Maps.newHashMap();
			if (overwrites!=null) {
				if (overwrites instanceof FDCompoundOverwrites) {
					// build mapping for compound fields
					for(FDField f : ((FDCompoundOverwrites)overwrites).getFields()) {
						this.mappedFields.put(f.getTarget(), f);
					}
				}
				if (overwrites instanceof FDEnumerationOverwrites) {
					// build mapping for enumerators
					for(FDEnumValue e : ((FDEnumerationOverwrites)overwrites).getEnumerators()) {
						this.mappedEnumerators.put(e.getTarget(), e);
					}
				}
			}
		}
		
		// host 'struct_fields'
		@Override
		public Integer getTag(FField obj) {
			// check if this field is overwritten
			if (mappedFields.containsKey(obj)) {
				FDField fo = mappedFields.get(obj);
				Integer v = target.getInteger(fo, "Tag");
				if (v!=null)
					return v;
			}
			return delegate.getTag(obj);
		}
		@Override
		public Boolean getIsOptional(FField obj) {
			// check if this field is overwritten
			if (mappedFields.containsKey(obj)) {
				FDField fo = mappedFields.get(obj);
				Boolean v = target.getBoolean(fo, "IsOptional");
				if (v!=null)
					return v;
			}
			return delegate.getIsOptional(obj);
		}
		@Override
		public String getDefaultValue(FField obj) {
			// check if this field is overwritten
			if (mappedFields.containsKey(obj)) {
				FDField fo = mappedFields.get(obj);
				String v = target.getString(fo, "DefaultValue");
				if (v!=null)
					return v;
			}
			return delegate.getDefaultValue(obj);
		}
		@Override
		public Ctype getCtype(FField obj) {
			// check if this field is overwritten
			if (mappedFields.containsKey(obj)) {
				FDField fo = mappedFields.get(obj);
				String e = target.getEnum(fo, "Ctype");
				if (e!=null) {
					return DataPropertyAccessorHelper.convertCtype(e);
				}
			}
			return delegate.getCtype(obj);
		}
		@Override
		public Boolean getPacked(FField obj) {
			// check if this field is overwritten
			if (mappedFields.containsKey(obj)) {
				FDField fo = mappedFields.get(obj);
				Boolean v = target.getBoolean(fo, "Packed");
				if (v!=null)
					return v;
			}
			return delegate.getPacked(obj);
		}
		@Override
		public String getExperimental_map_key(FField obj) {
			// check if this field is overwritten
			if (mappedFields.containsKey(obj)) {
				FDField fo = mappedFields.get(obj);
				String v = target.getString(fo, "Experimental_map_key");
				if (v!=null)
					return v;
			}
			return delegate.getExperimental_map_key(obj);
		}
		
		// host 'structs'
		@Override
		public Boolean getMessage_set_wire_format(FStructType obj) {
			if (overwrites!=null) {
				Boolean v = target.getBoolean(overwrites, "Message_set_wire_format");
				if (v!=null)
					return v;
			}
			return delegate.getMessage_set_wire_format(obj);
		}
		@Override
		public Boolean getNo_standard_descriptor_accessor(FStructType obj) {
			if (overwrites!=null) {
				Boolean v = target.getBoolean(overwrites, "No_standard_descriptor_accessor");
				if (v!=null)
					return v;
			}
			return delegate.getNo_standard_descriptor_accessor(obj);
		}
		
		
		@Override
		public IDataPropertyAccessor getOverwriteAccessor(FField obj) {
			// check if this field is overwritten
			if (mappedFields.containsKey(obj)) {
				FDField fo = mappedFields.get(obj);
				FDTypeOverwrites overwrites = fo.getOverwrites();
				if (overwrites==null)
					return this; // TODO: correct?
				else
					// TODO: this or delegate?
					return new OverwriteAccessor(overwrites, this, target);
				
			}
			return delegate.getOverwriteAccessor(obj);
		}
	
		@Override
		public IDataPropertyAccessor getOverwriteAccessor(FArrayType obj) {
			// check if this array is overwritten
			if (overwrites!=null) {
				// TODO: this or delegate?
				return new OverwriteAccessor(overwrites, this, target);
			}
			return delegate.getOverwriteAccessor(obj);
		}
	}
}
	
