/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.ProtobufSpec'
*******************************************************************************/
package org.franca.connectors.protobuf;

import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.ProtobufSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.ProtobufSpec.ProviderPropertyAccessor instead
 */
public class ProtobufSpecProviderPropertyAccessor
	extends org.franca.connectors.protobuf.ProtobufSpec.ProviderPropertyAccessor
	implements org.franca.connectors.protobuf.ProtobufSpec.Enums
{
	public ProtobufSpecProviderPropertyAccessor(FDeployedProvider target) {
		super(target);
	}
}
   
