/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.ProtobufSpec'
*******************************************************************************/
package org.franca.connectors.protobuf;

import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.ProtobufSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.ProtobufSpec.InterfacePropertyAccessor instead
 */
public class ProtobufSpecInterfacePropertyAccessor
	extends org.franca.connectors.protobuf.ProtobufSpec.InterfacePropertyAccessor
	implements org.franca.connectors.protobuf.ProtobufSpec.Enums
{
	public ProtobufSpecInterfacePropertyAccessor(FDeployedInterface target) {
		super(target);
	}
}
   
