/*
 * generated by Xtext
 */
package org.franca.core.dsl.scoping;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.resource.EObjectDescription;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.eclipse.xtext.scoping.impl.SimpleScope;
import org.franca.core.framework.FrancaHelpers;
import org.franca.core.franca.FContract;
import org.franca.core.franca.FDeclaration;
import org.franca.core.franca.FEventOnIf;
import org.franca.core.franca.FMethod;
import org.franca.core.franca.FState;
import org.franca.core.franca.FStateGraph;
import org.franca.core.franca.FStateTerminal;
import org.franca.core.franca.FTrigger;
import org.franca.core.franca.FTriggeredTransition;

import com.google.common.collect.Lists;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping on
 * how and when to use it
 * 
 */
public class FrancaIDLScopeProvider extends AbstractDeclarativeScopeProvider {

	/**
	 * returns a flat list of State scopes for a {@link FStateTerminal}
	 * @param st - the transition endpoint or terminal
	 * @param ref - not used
	 * @return a list of scopes
	 */
	public IScope scope_FStateTerminal_state(FStateTerminal st, EReference ref) {
		return getStateScopes(st);
	}

	
	private IScope getStateScopes(EObject obj) {
		final List<IEObjectDescription> scopes = Lists.newArrayList();

		// first state in container hierarchy
		FStateGraph parent = FrancaHelpers.getStateGraph(obj);

		// collect states of my parent
		if (parent != null) {
			for (FState s : parent.getStates()) {
				scopes.add(EObjectDescription.create(s.getName(), s));
			}
		}
		return new SimpleScope(IScope.NULLSCOPE, scopes);
	}

	
	public IScope scope_FAssignment_lhs (FContract contract, EReference ref) {
		return Scopes.scopeFor(contract.getVariables());
	}

	
	public IScope scope_FTypedElementRef_element (FTriggeredTransition tr, EReference ref) {
		final List<EObject> scopes = Lists.newArrayList();

		// add state variables of the enclosing contract to this scope
		FContract contract = FrancaHelpers.getContract(tr);
		System.out.println("Scope " + tr.getTrigger().getEvent().toString());
		if (contract!=null) { 
			scopes.addAll(contract.getVariables());
			for(FDeclaration d : contract.getVariables()) {
				System.out.println("  var " + d.getName());
			}
		}

		// add the trigger's parameters to this scope
		FEventOnIf ev = tr.getTrigger().getEvent();
		if (ev.getCall()!=null) {
			scopes.addAll(ev.getCall().getInArgs());
		} else if (ev.getRespond()!=null) {
			scopes.addAll(ev.getRespond().getOutArgs());
		} else if (ev.getSignal()!=null) {
			scopes.addAll(ev.getSignal().getOutArgs());
		}

		return Scopes.scopeFor(scopes);
	}

}
