/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'dummy_package.ServiceWithOneRPCSpec'
*******************************************************************************/
package dummy_package;

import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'dummy_package.ServiceWithOneRPCSpec' specification
 *
 * @deprecated use class dummy_package.ServiceWithOneRPCSpec.ProviderPropertyAccessor instead
 */
public class ServiceWithOneRPCSpecProviderPropertyAccessor
	extends dummy_package.ServiceWithOneRPCSpec.ProviderPropertyAccessor
	implements dummy_package.ServiceWithOneRPCSpec.Enums
{
	public ServiceWithOneRPCSpecProviderPropertyAccessor(FDeployedProvider target) {
		super(target);
	}
}
   
