/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'dummy_package.ServiceWithOneRPCSpec'
*******************************************************************************/
package dummy_package;

import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'dummy_package.ServiceWithOneRPCSpec' specification
 *
 * @deprecated use class dummy_package.ServiceWithOneRPCSpec.InterfacePropertyAccessor instead
 */
public class ServiceWithOneRPCSpecInterfacePropertyAccessor
	extends dummy_package.ServiceWithOneRPCSpec.InterfacePropertyAccessor
	implements dummy_package.ServiceWithOneRPCSpec.Enums
{
	public ServiceWithOneRPCSpecInterfacePropertyAccessor(FDeployedInterface target) {
		super(target);
	}
}
   
