/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'dummy_package.ServiceWithOneRPCSpec'
*******************************************************************************/
package dummy_package;

import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'dummy_package.ServiceWithOneRPCSpec' specification
 *
 * @deprecated use class dummy_package.ServiceWithOneRPCSpec.TypeCollectionPropertyAccessor instead
 */
public class ServiceWithOneRPCSpecTypeCollectionPropertyAccessor
	extends dummy_package.ServiceWithOneRPCSpec.TypeCollectionPropertyAccessor
	implements dummy_package.ServiceWithOneRPCSpec.Enums
{
	public ServiceWithOneRPCSpecTypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
		super(target);
	}
}
   
