<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="franca" nsURI="http://core.franca.org" nsPrefix="franca">
  <eClassifiers xsi:type="ecore:EClass" name="FModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The root class of a Franca model.&#xD;&#xA;It contains a list of interfaces and a set of type collections.&#xD;&#xA;Other Franca models might be referenced by the 'imports' attribute.&#xD;&#xA;The name of a Franca model is the package declaration. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="#//FInterface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeCollections" upperBound="-1"
        eType="#//FTypeCollection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An import declaration.&#xD;&#xA;It defines a namespace from some Franca resource, which&#xD;&#xA;should be imported. All elements from other Franca models&#xD;&#xA;referenced by this model should be member of some&#xD;&#xA;imported Franca model.&#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FTypeCollection" eSuperTypes="#//FModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A collection of Franca type definitions.&#xD;&#xA;The type collection is named and should be versioned (optional).&#xD;&#xA;Types defined by a FTypeCollection can be referenced from&#xD;&#xA;other FTypeCollections and FInterfaces.&#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="#//FVersion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//FType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FInterface" eSuperTypes="#//FTypeCollection">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents a Franca interface definition.&#xD;&#xA;Interfaces are named and should be versioned (optional).&#xD;&#xA;Types defined as part of this interface can not be referenced&#xD;&#xA;by other FTypeCollections and FInterfaces. This type visibility&#xD;&#xA;differs from the types defined as part of FTypeCollections.&#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//FAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//FMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="broadcasts" upperBound="-1"
        eType="#//FBroadcast" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contract" eType="#//FContract"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" eType="#//FInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managedInterfaces" upperBound="-1"
        eType="#//FInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FMethod" eSuperTypes="#//FModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The definition of a Franca method as part of an FInterface.&#xD;&#xA;Methods without out arguments might have be flagged as&#xD;&#xA;'fireAndForget'. See the Franca IDL chapter in the Franca&#xD;&#xA;User Guide for very detailed information on method semantics.&#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fireAndForget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inArgs" upperBound="-1"
        eType="#//FArgument" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outArgs" upperBound="-1"
        eType="#//FArgument" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorEnum" eType="#//FEnumerationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errors" eType="#//FEnumerationType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBroadcast" eSuperTypes="#//FModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The definition of a Franca broadcast as part of an FInterface.&#xD;&#xA;See the Franca IDL chapter in the Franca User Guide for very&#xD;&#xA;detailed information on broadcast semantics.&#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outArgs" upperBound="-1"
        eType="#//FArgument" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selective" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FAttribute" eSuperTypes="#//FTypedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The definition of a Franca attribute as part of an FInterface.&#xD;&#xA;See the Franca IDL chapter in the Franca User Guide for very&#xD;&#xA;detailed information on attribute semantics and the flags&#xD;&#xA;which can be set for attributes.&#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noSubscriptions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FArgument" eSuperTypes="#//FTypedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents an argument (aka parameter) for&#xD;&#xA;a FMethod or FBroadcast. For methods, this might be&#xD;&#xA;an input or output argument. For FBroadcasts, there are only&#xD;&#xA;output arguments (i.e., from server to client).&#xD;&#xA;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FType" abstract="true" eSuperTypes="#//FModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is the base class for all user-defined Franca types.&#xD;&#xA;It will never be instantiated directly."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FModelElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" eType="#//FAnnotationBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FVersion">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The version of this interface or type collection.&#xD;&#xA;It is defined according to the Apache major/minor scheme for interfaces.&#xD;&#xA;I.e., a change in the major number indicates a non-compatible change.&#xD;&#xA;It is mandatory to define both major and minor numbers."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="major" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FBasicTypeId">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This enum represents the basic types available in Franca IDL.&#xD;&#xA;See section ref:FIDL_PrimitiveTypes[Primitive types] in the&#xD;&#xA;Franca User Guide for a list of available primitive types and their semantics.&#xD;&#xA;"/>
    </eAnnotations>
    <eLiterals name="undefined" literal="undefined"/>
    <eLiterals name="Int8" value="1" literal="Int8"/>
    <eLiterals name="UInt8" value="2" literal="UInt8"/>
    <eLiterals name="Int16" value="3" literal="Int16"/>
    <eLiterals name="UInt16" value="4" literal="UInt16"/>
    <eLiterals name="Int32" value="5" literal="Int32"/>
    <eLiterals name="UInt32" value="6" literal="UInt32"/>
    <eLiterals name="Int64" value="7" literal="Int64"/>
    <eLiterals name="UInt64" value="8" literal="UInt64"/>
    <eLiterals name="Boolean" value="9" literal="Boolean"/>
    <eLiterals name="String" value="10" literal="String"/>
    <eLiterals name="Float" value="11" literal="Float"/>
    <eLiterals name="Double" value="12" literal="Double"/>
    <eLiterals name="ByteBuffer" value="13" literal="ByteBuffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FArrayType" eSuperTypes="#//FType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" lowerBound="1"
        eType="#//FTypeRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FCompoundType" abstract="true" eSuperTypes="#//FType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents all kinds of compound types in Franca, i.e., struct and union types.&#xA;A compound type has a list of fields; each field is itself specified by its type.&#xA;Thus, nested compounds can be created.&#xA;The ordering of fields in the compound is relevant. E.g., serialization code&#xA;generated from a Franca interface must take into account the order of the fields.&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//FField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FTypeDef" eSuperTypes="#//FType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualType" lowerBound="1"
        eType="#//FTypeRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FTypedElement" abstract="true" eSuperTypes="#//FModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//FTypeRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FVariable" eSuperTypes="#//FTypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FStructType" eSuperTypes="#//FCompoundType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents a struct type in Franca. See its base class&#xA;ref:FrancaModelAPIReference_FCompoundType[FCompoundType]&#xA;for a detailed description."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" eType="#//FStructType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="polymorphic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FEnumerator" eSuperTypes="#//FModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FEnumerationType" eSuperTypes="#//FType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents an enumeration type. The enumeration will contain&#xA;a list of e[enumerators]. It can be derived from a base enumeration."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumerators" upperBound="-1"
        eType="#//FEnumerator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" eType="#//FEnumerationType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FMapType" eSuperTypes="#//FType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The Franca map type (sometimes &quot;map&quot; is also called &quot;dictionary&quot;).&#xA;This is a collection type which maps objects of a e[key] type to objects&#xA;of a e[value] type in constant time."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyType" lowerBound="1"
        eType="#//FTypeRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueType" lowerBound="1"
        eType="#//FTypeRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FTypeRef">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class is a reference to some Franca type.&#xA;It may be either a ref:FIDL_PrimitiveTypes[primitive&#xA;type] (property e[predefined] or a derived type (e.g., struct, array, map).&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predefined" eType="#//FBasicTypeId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="derived" eType="#//FType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FAnnotationType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This enum represents the type of a structured comment (i.e., the tag starting with a '@').&#xD;&#xA;"/>
    </eAnnotations>
    <eLiterals name="description" value="1" literal="@description"/>
    <eLiterals name="author" value="2" literal="@author"/>
    <eLiterals name="experimental" value="3" literal="@experimental"/>
    <eLiterals name="deprecated" value="4" literal="@deprecated"/>
    <eLiterals name="see" value="5" literal="@see"/>
    <eLiterals name="param" value="6" literal="@param"/>
    <eLiterals name="high_volume" value="8" literal="@high-volume"/>
    <eLiterals name="high_frequency" value="9" literal="@high-frequency"/>
    <eLiterals name="source_uri" value="10" literal="@source-uri"/>
    <eLiterals name="source_alias" value="11" literal="@source-alias"/>
    <eLiterals name="details" value="12" literal="@details"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//FAnnotationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FAnnotationBlock">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents a structured comment.&#xD;&#xA;It is used by many of the elements of the Franca IDL model.&#xD;&#xA;A structured comment consists of a list of elements with one tagged comment each.&#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//FAnnotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FContract">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The contract for a Franca interface.&#xD;&#xA;The contract specifies the dynamic behaviour of the interface.&#xD;&#xA;It consists of a PSM (short for: Protocol State Machine) and&#xD;&#xA;an optional set of state variables."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateGraph" lowerBound="1"
        eType="#//FStateGraph" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//FDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FDeclaration" eSuperTypes="#//FTypedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents the definition of a state variable&#xD;&#xA;as part of a Franca interface contract. Note that the &#xD;&#xA;types available for the state variable definition are &#xD;&#xA;all types which are accessible from this interface."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FStateGraph">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A state graph specifying the interface's dynamic behavior. The state graph is flat&#xA;(i.e., non-hierarchical) and consists of a set of states, which are linked by transitions.&#xA;One of the states in the set is specified as e[initial]. I.e., this is the initial state of the interface."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial" lowerBound="1"
        eType="#//FState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//FState" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FState" eSuperTypes="#//FModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents a single state as member of a &#xA;ref:FrancaModelAPIReference_FStateGraph[FStateGraph].&#xA;The state contains a list of its outgoing transitions. &#xA;The target state of each transition is contained in that transition."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//FTransition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FTransition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents a single transition as part of a &#xA;ref:FrancaModelAPIReference_FStateGraph[FStateGraph].&#xA;The transition references its target state by property e[to]. &#xA;It doesn't reference its source state; instead, the source state contains&#xA;the list of its outgoing transitions.&#xA;The transition defines a e[trigger], which specifies some event which&#xA;can occur during runtime. It also defines a e[guard] condition.&#xA;If the trigger event occurs, the guard condition will be checked (if any).&#xA;Depending on this check the transition will be executed.&#xA;Finally, a transition has some e[action], which will be executed&#xA;each time when the transition fires."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" lowerBound="1"
        eType="#//FTrigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//FGuard"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//FState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//FExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FTrigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="#//FEventOnIf"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FEventOnIf">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents a communication event,&#xD;&#xA;which basically corresponds to a message on the interface.&#xD;&#xA;Exactly one of its properties should be set, all other should be zero.&#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="call" eType="#//FMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="respond" eType="#//FMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" eType="#//FBroadcast"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" eType="#//FAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="update" eType="#//FAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FGuard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//FExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FUnionType" eSuperTypes="#//FCompoundType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents a union type in Franca. See its base class&#xA;ref:FrancaModelAPIReference_FCompoundType[FCompoundType]&#xA;for a detailed description."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" eType="#//FUnionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FField" eSuperTypes="#//FTypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FBlockExpression" eSuperTypes="#//FExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//FExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FAssignment" eSuperTypes="#//FExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//FDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//FExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FExpression" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is the common base class for all expressions of&#xD;&#xA;the Franca contract action language.&#xD;&#xA;The FExpression class will never be instantiated.&#xD;&#xA;"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FTypedElementRef" eSuperTypes="#//FExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class is a reference to some ref:FrancaModelAPIReference_FTypedElement[FTypedElement].&#xA;If the referenced element is no compound type (i.e., struct or union), only the e[element] property&#xA;will be used. The e[target] and e[field] properties will be null. If a field of a compound type is referenced,&#xA;the e[field] property will point to the ref:FrancaModelAPIReference_FField[FField] object. &#xA;If the compound type is nested, the e[target] property will reference the next outer level&#xA;(which is itself a compound referenced by a ref:FrancaModelAPIReference_FTypedElementRef[FTypedElementRef]. &#xA;This might be chained in order to specify a reference to a deeply nested compound element.&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//FTypedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//FTypedElementRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//FField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FConstant" abstract="true" eSuperTypes="#//FExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is the common base class for all kinds of&#xD;&#xA;constants in the Franca contract action language.&#xD;&#xA;The most important types are integers, booleans and strings."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FIntegerConstant" eSuperTypes="#//FConstant">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents integer constants in the Franca contract action language."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBooleanConstant" eSuperTypes="#//FConstant">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents boolean constants in the Franca contract action language."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FStringConstant" eSuperTypes="#//FConstant">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents strings constants in the Franca contract action language."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBinaryOperation" eSuperTypes="#//FExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//FExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//FExpression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
