/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.EmptyServiceSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.EmptyServiceSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.EmptyServiceSpec.ProviderPropertyAccessor instead
 */
public class EmptyServiceSpecProviderPropertyAccessor
	extends org.franca.connectors.protobuf.tests.EmptyServiceSpec.ProviderPropertyAccessor
	implements org.franca.connectors.protobuf.tests.EmptyServiceSpec.Enums
{
	public EmptyServiceSpecProviderPropertyAccessor(FDeployedProvider target) {
		super(target);
	}
}
   
