/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.EmptyMessageSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.EmptyMessageSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.EmptyMessageSpec.TypeCollectionPropertyAccessor instead
 */
public class EmptyMessageSpecTypeCollectionPropertyAccessor
	extends org.franca.connectors.protobuf.tests.EmptyMessageSpec.TypeCollectionPropertyAccessor
	implements org.franca.connectors.protobuf.tests.EmptyMessageSpec.Enums
{
	public EmptyMessageSpecTypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
		super(target);
	}
}
   
