/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.EmptyServiceSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.EmptyServiceSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.EmptyServiceSpec.InterfacePropertyAccessor instead
 */
public class EmptyServiceSpecInterfacePropertyAccessor
	extends org.franca.connectors.protobuf.tests.EmptyServiceSpec.InterfacePropertyAccessor
	implements org.franca.connectors.protobuf.tests.EmptyServiceSpec.Enums
{
	public EmptyServiceSpecInterfacePropertyAccessor(FDeployedInterface target) {
		super(target);
	}
}
   
