/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.EmptyMessageSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.EmptyMessageSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.EmptyMessageSpec.InterfacePropertyAccessor instead
 */
public class EmptyMessageSpecInterfacePropertyAccessor
	extends org.franca.connectors.protobuf.tests.EmptyMessageSpec.InterfacePropertyAccessor
	implements org.franca.connectors.protobuf.tests.EmptyMessageSpec.Enums
{
	public EmptyMessageSpecInterfacePropertyAccessor(FDeployedInterface target) {
		super(target);
	}
}
   
