/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.EmptyMessageSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.EmptyMessageSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.EmptyMessageSpec.ProviderPropertyAccessor instead
 */
public class EmptyMessageSpecProviderPropertyAccessor
	extends org.franca.connectors.protobuf.tests.EmptyMessageSpec.ProviderPropertyAccessor
	implements org.franca.connectors.protobuf.tests.EmptyMessageSpec.Enums
{
	public EmptyMessageSpecProviderPropertyAccessor(FDeployedProvider target) {
		super(target);
	}
}
   
