/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.EmptyServiceSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.EmptyServiceSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.EmptyServiceSpec.TypeCollectionPropertyAccessor instead
 */
public class EmptyServiceSpecTypeCollectionPropertyAccessor
	extends org.franca.connectors.protobuf.tests.EmptyServiceSpec.TypeCollectionPropertyAccessor
	implements org.franca.connectors.protobuf.tests.EmptyServiceSpec.Enums
{
	public EmptyServiceSpecTypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
		super(target);
	}
}
   
