/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec.TypeCollectionPropertyAccessor instead
 */
public class Enum_enumeratorValueSpecTypeCollectionPropertyAccessor
	extends org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec.TypeCollectionPropertyAccessor
	implements org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec.Enums
{
	public Enum_enumeratorValueSpecTypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
		super(target);
	}
}
   
