/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec.ProviderPropertyAccessor instead
 */
public class Enum_enumeratorValueSpecProviderPropertyAccessor
	extends org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec.ProviderPropertyAccessor
	implements org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec.Enums
{
	public Enum_enumeratorValueSpecProviderPropertyAccessor(FDeployedProvider target) {
		super(target);
	}
}
   
