/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec.InterfacePropertyAccessor instead
 */
public class Enum_enumeratorValueSpecInterfacePropertyAccessor
	extends org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec.InterfacePropertyAccessor
	implements org.franca.connectors.protobuf.tests.Enum_enumeratorValueSpec.Enums
{
	public Enum_enumeratorValueSpecInterfacePropertyAccessor(FDeployedInterface target) {
		super(target);
	}
}
   
