/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec.TypeCollectionPropertyAccessor instead
 */
public class Enum_emptyEnumSpecTypeCollectionPropertyAccessor
	extends org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec.TypeCollectionPropertyAccessor
	implements org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec.Enums
{
	public Enum_emptyEnumSpecTypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
		super(target);
	}
}
   
