/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec.ProviderPropertyAccessor instead
 */
public class Enum_emptyEnumSpecProviderPropertyAccessor
	extends org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec.ProviderPropertyAccessor
	implements org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec.Enums
{
	public Enum_emptyEnumSpecProviderPropertyAccessor(FDeployedProvider target) {
		super(target);
	}
}
   
