/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec.InterfacePropertyAccessor instead
 */
public class Enum_emptyEnumSpecInterfacePropertyAccessor
	extends org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec.InterfacePropertyAccessor
	implements org.franca.connectors.protobuf.tests.Enum_emptyEnumSpec.Enums
{
	public Enum_emptyEnumSpecInterfacePropertyAccessor(FDeployedInterface target) {
		super(target);
	}
}
   
