/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec.TypeCollectionPropertyAccessor instead
 */
public class MessageWithScalarValueTypeFieldsSpecTypeCollectionPropertyAccessor
	extends org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec.TypeCollectionPropertyAccessor
	implements org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec.Enums
{
	public MessageWithScalarValueTypeFieldsSpecTypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
		super(target);
	}
}
   
