/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec.ProviderPropertyAccessor instead
 */
public class MessageWithScalarValueTypeFieldsSpecProviderPropertyAccessor
	extends org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec.ProviderPropertyAccessor
	implements org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec.Enums
{
	public MessageWithScalarValueTypeFieldsSpecProviderPropertyAccessor(FDeployedProvider target) {
		super(target);
	}
}
   
