/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec.InterfacePropertyAccessor instead
 */
public class MessageWithScalarValueTypeFieldsSpecInterfacePropertyAccessor
	extends org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec.InterfacePropertyAccessor
	implements org.franca.connectors.protobuf.tests.messageWithScalarValueTypeFieldsSpec.Enums
{
	public MessageWithScalarValueTypeFieldsSpecInterfacePropertyAccessor(FDeployedInterface target) {
		super(target);
	}
}
   
