/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.NameNotUniqueSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.NameNotUniqueSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.NameNotUniqueSpec.ProviderPropertyAccessor instead
 */
public class NameNotUniqueSpecProviderPropertyAccessor
	extends org.franca.connectors.protobuf.tests.NameNotUniqueSpec.ProviderPropertyAccessor
	implements org.franca.connectors.protobuf.tests.NameNotUniqueSpec.Enums
{
	public NameNotUniqueSpecProviderPropertyAccessor(FDeployedProvider target) {
		super(target);
	}
}
   
