/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.NameNotUniqueSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.NameNotUniqueSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.NameNotUniqueSpec.InterfacePropertyAccessor instead
 */
public class NameNotUniqueSpecInterfacePropertyAccessor
	extends org.franca.connectors.protobuf.tests.NameNotUniqueSpec.InterfacePropertyAccessor
	implements org.franca.connectors.protobuf.tests.NameNotUniqueSpec.Enums
{
	public NameNotUniqueSpecInterfacePropertyAccessor(FDeployedInterface target) {
		super(target);
	}
}
   
