/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.NameNotUniqueSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.NameNotUniqueSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.NameNotUniqueSpec.TypeCollectionPropertyAccessor instead
 */
public class NameNotUniqueSpecTypeCollectionPropertyAccessor
	extends org.franca.connectors.protobuf.tests.NameNotUniqueSpec.TypeCollectionPropertyAccessor
	implements org.franca.connectors.protobuf.tests.NameNotUniqueSpec.Enums
{
	public NameNotUniqueSpecTypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
		super(target);
	}
}
   
