/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.NestedExtensionsSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.NestedExtensionsSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.NestedExtensionsSpec.ProviderPropertyAccessor instead
 */
public class NestedExtensionsSpecProviderPropertyAccessor
	extends org.franca.connectors.protobuf.tests.NestedExtensionsSpec.ProviderPropertyAccessor
	implements org.franca.connectors.protobuf.tests.NestedExtensionsSpec.Enums
{
	public NestedExtensionsSpecProviderPropertyAccessor(FDeployedProvider target) {
		super(target);
	}
}
   
