/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.NestedExtensionsSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.NestedExtensionsSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.NestedExtensionsSpec.InterfacePropertyAccessor instead
 */
public class NestedExtensionsSpecInterfacePropertyAccessor
	extends org.franca.connectors.protobuf.tests.NestedExtensionsSpec.InterfacePropertyAccessor
	implements org.franca.connectors.protobuf.tests.NestedExtensionsSpec.Enums
{
	public NestedExtensionsSpecInterfacePropertyAccessor(FDeployedInterface target) {
		super(target);
	}
}
   
