/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.NestedExtensionsSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.NestedExtensionsSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.NestedExtensionsSpec.TypeCollectionPropertyAccessor instead
 */
public class NestedExtensionsSpecTypeCollectionPropertyAccessor
	extends org.franca.connectors.protobuf.tests.NestedExtensionsSpec.TypeCollectionPropertyAccessor
	implements org.franca.connectors.protobuf.tests.NestedExtensionsSpec.Enums
{
	public NestedExtensionsSpecTypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
		super(target);
	}
}
   
