/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.OptionSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.OptionSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.OptionSpec.ProviderPropertyAccessor instead
 */
public class OptionSpecProviderPropertyAccessor
	extends org.franca.connectors.protobuf.tests.OptionSpec.ProviderPropertyAccessor
	implements org.franca.connectors.protobuf.tests.OptionSpec.Enums
{
	public OptionSpecProviderPropertyAccessor(FDeployedProvider target) {
		super(target);
	}
}
   
