/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.OptionSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.OptionSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.OptionSpec.TypeCollectionPropertyAccessor instead
 */
public class OptionSpecTypeCollectionPropertyAccessor
	extends org.franca.connectors.protobuf.tests.OptionSpec.TypeCollectionPropertyAccessor
	implements org.franca.connectors.protobuf.tests.OptionSpec.Enums
{
	public OptionSpecTypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
		super(target);
	}
}
   
