/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.franca.connectors.protobuf.tests.OptionSpec'
*******************************************************************************/
package org.franca.connectors.protobuf.tests;

import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'org.franca.connectors.protobuf.tests.OptionSpec' specification
 *
 * @deprecated use class org.franca.connectors.protobuf.tests.OptionSpec.InterfacePropertyAccessor instead
 */
public class OptionSpecInterfacePropertyAccessor
	extends org.franca.connectors.protobuf.tests.OptionSpec.InterfacePropertyAccessor
	implements org.franca.connectors.protobuf.tests.OptionSpec.Enums
{
	public OptionSpecInterfacePropertyAccessor(FDeployedInterface target) {
		super(target);
	}
}
   
