/*
 * generated by Xtext
 */
package org.franca.deploymodel.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FDeployRuntimeModule extends org.franca.deploymodel.dsl.AbstractFDeployRuntimeModule {

}
