/*
 * generated by Xtext
 */
package org.franca.deploymodel.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FDeployUiModule extends org.franca.deploymodel.dsl.ui.AbstractFDeployUiModule {
	public FDeployUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
