/*
* generated by Xtext
*/
package org.franca.deploymodel.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class FDeployOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
