/*
 * generated by Xtext
 */
package org.franca.core.dsl.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider
import org.franca.core.franca.FTypeDef

/** 
 * customization of the default outline structure
 */
class FrancaIDLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	def protected boolean _isLeaf(FTypeDef feature) {
		return true
	}
}
