/*
* generated by Xtext
*/
package org.franca.core.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class FrancaIDLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
