name: Build 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: mvn -f releng/org.franca.parent --batch-mode --update-snapshots clean verify
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          check_name: "Test Results"
          report_paths: 'build/tests/*/target/surefire-reports/*.xml, build/examples/*/target/surefire-reports/*.xml'
          fail_on_failure: true
          summary: true