/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment spec 'org.example.spec.SpecCompoundHosts'
*******************************************************************************/
package org.example.spec;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.franca.core.franca.FField;
import org.franca.core.franca.FArgument;
import org.franca.core.franca.FAttribute;
import org.franca.core.franca.FModelElement;
import org.franca.deploymodel.core.FDeployedInterface;
import org.franca.deploymodel.core.FDeployedTypeCollection;
import org.franca.deploymodel.dsl.fDeploy.FDArgument;
import org.franca.deploymodel.dsl.fDeploy.FDAttribute;
import org.franca.deploymodel.dsl.fDeploy.FDCompoundOverwrites;
import org.franca.deploymodel.dsl.fDeploy.FDElement;
import org.franca.deploymodel.dsl.fDeploy.FDField;
import org.franca.deploymodel.dsl.fDeploy.FDFieldOverwrite;
import org.franca.deploymodel.dsl.fDeploy.FDOverwriteElement;
import org.franca.deploymodel.dsl.fDeploy.FDProperty;

/**
 * Accessor for deployment properties for 'org.example.spec.SpecCompoundHosts' specification
 */		
public class SpecCompoundHostsTypeCollectionPropertyAccessorRef extends AbstractSpecCompoundHostsDataPropertyAccessor
{
	public SpecCompoundHostsTypeCollectionPropertyAccessorRef (FDeployedTypeCollection target) {
		super(target);
	}
	
	@Override
	public StringProp getStringProp (EObject obj) {
		String e = target.getEnum(obj, "StringProp");
		if (e==null) return null;
		return convertStringProp(e);
	}
	
	@Override
	public Integer getArrayProp (EObject obj) {
		return target.getInteger(obj, "ArrayProp");
	}
	
	public Integer getStructProp (EObject obj) {
		return target.getInteger(obj, "StructProp");
	}
	
	@Override
	public Integer getSFieldProp (FField obj) {
		return target.getInteger(obj, "SFieldProp");
	}
	
	public Integer getUnionProp (EObject obj) {
		return target.getInteger(obj, "UnionProp");
	}
	
	@Override
	public Integer getUFieldProp (FField obj) {
		return target.getInteger(obj, "UFieldProp");
	}
	


	@Override
	public ISpecCompoundHostsDataPropertyAccessor getOverwriteAccessor (FField obj) {
		return getOverwriteAccessorAux(obj);
	}
	
}
